using CloudNimble.SimpleMessageBus.Core;
using Confluent.Kafka;
using Microsoft.Extensions.Options;
using System;
using System.Threading.Tasks;

namespace CloudNimble.SimpleMessageBus.Publish.Kafka
{

    /// <summary>
    /// Manages the process of publishing MessageBus messages to Apache Kafka.
    /// </summary>
    /// <remarks>
    /// <para>
    /// This publisher integrates with Apache Kafka using the Confluent.Kafka client library.
    /// It handles message serialization, producer initialization, and optional message key routing.
    /// </para>
    /// <para>
    /// For advanced partitioning control, implement <see cref="IKafkaKeyProvider"/> on your
    /// message types. Messages with the same key are guaranteed to be delivered to the same
    /// partition in order.
    /// </para>
    /// </remarks>
    /// <example>
    /// <code>
    /// // Basic usage
    /// await publisher.PublishAsync(new MyMessage { Data = "Hello" });
    ///
    /// // With partition key for ordering
    /// await publisher.PublishAsync(new OrderMessage { OrderId = "123" }); // Implements IKafkaKeyProvider
    /// </code>
    /// </example>
    public class KafkaMessagePublisher : IMessagePublisher, IDisposable
    {

        #region Private Members

        private readonly KafkaOptions _options;
        private IProducer<string, string> _producer;
        private bool _disposed;

        #endregion

        #region Properties

        /// <summary>
        /// The Kafka producer instance. Lazily initialized on first use.
        /// </summary>
        internal IProducer<string, string> Producer
        {
            get
            {
                _producer ??= CreateProducer();

                return _producer;
            }
        }

        #endregion

        #region Constructors

        /// <summary>
        /// Creates a new instance of <see cref="KafkaMessagePublisher"/>.
        /// </summary>
        /// <param name="options">The Kafka configuration options. Should be registered with your Dependency Injection container.</param>
        /// <exception cref="ArgumentNullException">Thrown when <paramref name="options"/> is null.</exception>
        /// <exception cref="ArgumentException">Thrown when required configuration properties are missing.</exception>
        public KafkaMessagePublisher(IOptions<KafkaOptions> options)
        {
            ArgumentNullException.ThrowIfNull(options);
            ArgumentException.ThrowIfNullOrWhiteSpace(options.Value.BrokerList, nameof(options.Value.BrokerList));
            ArgumentException.ThrowIfNullOrWhiteSpace(options.Value.TopicName, nameof(options.Value.TopicName));

            _options = options.Value;
        }

        #endregion

        #region Public Methods

        /// <summary>
        /// Disposes the Kafka producer and releases resources.
        /// </summary>
        public void Dispose()
        {
            Dispose(true);
            GC.SuppressFinalize(this);
        }

        /// <summary>
        /// Publishes a message to the configured Kafka topic.
        /// </summary>
        /// <param name="message">The <see cref="IMessage"/> to wrap in a <see cref="MessageEnvelope"/> and publish to Kafka.</param>
        /// <param name="isSystemGenerated">Specifies whether or not the event was generated by the system. (Not currently used).</param>
        /// <returns>A <see cref="Task"/> reference for the asynchronous function.</returns>
        /// <remarks>
        /// <para>
        /// If the message implements <see cref="IKafkaKeyProvider"/>, the key will be used
        /// to route the message to a specific partition, ensuring ordering for messages
        /// with the same key.
        /// </para>
        /// <para>
        /// Messages are serialized using <see cref="MessageEnvelope"/> which includes metadata
        /// such as the message ID, timestamp, and type information for deserialization.
        /// </para>
        /// </remarks>
        /// <exception cref="ArgumentNullException">Thrown when <paramref name="message"/> is null.</exception>
        public async Task PublishAsync(IMessage message, bool isSystemGenerated = false)
        {
            ArgumentNullException.ThrowIfNull(message);

            // Wrap the entity in a MessageEnvelope.
            var envelope = new MessageEnvelope(message);
            var key = message is IKafkaKeyProvider keyProvider ? keyProvider.GetKafkaKey() : null;

            var kafkaMessage = new Message<string, string>
            {
                Key = key,
                Value = envelope.ToString()
            };

            var result = await Producer.ProduceAsync(_options.TopicName, kafkaMessage).ConfigureAwait(false);
            Console.WriteLine($"Message delivered to {result.TopicPartitionOffset}");
        }

        #endregion

        #region Private Methods

        private IProducer<string, string> CreateProducer()
        {
            var config = new ProducerConfig
            {
                BootstrapServers = _options.BrokerList,
                EnableDeliveryReports = true
            };

            // Configure security if specified
            if (_options.Protocol != KafkaBrokerProtocol.Plaintext)
            {
                config.SecurityProtocol = (SecurityProtocol)(int)_options.Protocol;
            }

            if (_options.AuthenticationMode != KafkaAuthenticationMode.NotSet)
            {
                config.SaslMechanism = (SaslMechanism)(int)_options.AuthenticationMode;
                config.SaslUsername = _options.Username;
                config.SaslPassword = _options.Password;
            }

            if (!string.IsNullOrWhiteSpace(_options.SslCaLocation))
            {
                config.SslCaLocation = _options.SslCaLocation;
            }

            return new ProducerBuilder<string, string>(config).Build();
        }

        /// <summary>
        /// Disposes managed and unmanaged resources.
        /// </summary>
        /// <param name="disposing">True if called from <see cref="Dispose()"/>, false if called from finalizer.</param>
        protected virtual void Dispose(bool disposing)
        {
            if (!_disposed)
            {
                if (disposing)
                {
                    _producer?.Flush(TimeSpan.FromSeconds(10));
                    _producer?.Dispose();
                }

                _disposed = true;
            }
        }

        #endregion

    }

}
